export default {
  HOME: 'Home Tab',
  REWARD: 'Reward Tab',
  MORE_STACK: 'More Tab',
  MENU: 'Menu Tab',
  MENU_STACK: 'Menu Stack',
  MAIN: 'Main',
  MAIN_STACK: 'Main Stack',
  PROFILE: 'Profile',
  AUTOMATION: 'Automation',
  M_BOT: 'Push Notifications',
  MARKET_PLACE: 'Public Listings',
  BUSINESS_REGISTRATION: 'Bussiness Registration',
  INTEGRATION: 'Integration',
  SUPPORT: 'Support',
  STORE_SETTINGS: 'Store Settings',
  // Auth
  LOGIN: 'Login',
  REGISTRATION: 'Registration',
  RESET_PASSWORD: 'Reset Password',
  RESET_PASSWORD_DONE: 'Reset Password Done',
  RESET_PASSWORD_SUCCESS: 'Reset Password Success',
  RESET_PASSWORD_FAIL: 'Reset Password Fail',
  CREATE_PASSWORD: 'Create Password',
  VERIFY_EMAIL: 'Verify Email',
  CHANGE_PASSWORD: 'Change Password',
  LOGOUT: 'Logout',
  // Wallet
  WALLET_STACK: 'Wallet Tab',
  WALLET: 'Wallet',
  CHOOSE_PAYMENT_METHOD: 'Choose payment method',
  BANK_TRANSFER: 'Bank Transfer',
  SEND_FUNDS: 'Send Funds',
  // More
  MORE: 'More',

  // Store front -> Analytic
  ANALYTICS: 'Analytics',
  SALES_ANALYTICS: 'Sales Analytics',
  PRODUCT_ANALYTICS: 'Product Analytics',
  CUSTOMER_ANALYTICS: 'Customer Analytics',
  // Store front -> Products
  PRODUCTS_TAB: 'Products Tab',
  PRODUCTS_STACK: 'Products Stack',
  PRODUCTS: 'Products',
  NEW_PRODUCT: 'New Product',
  EDIT_PRODUCT: 'Edit Product',
  // Store front -> Category
  CATEGORY: 'Category',
  NEW_CATEGORY: 'New Category',
  EDIT_CATEGORY: 'Edit Category',
  // Store front -> Coupon
  COUPON: 'Coupon',
  // Store front -> Tax
  TAX: 'Tax',
  // Marketing suite
  ENGAGEMNT_TAB: 'Engagement tab',
  ENGAGEMNT: 'Engagement',
  CAMPAIGN: 'Campaign',
  NEW_CAMPAIGN: 'Create New Campaign',
  EDIT_CAMPAIGN: 'Edit Campaign',
  CONTACTS: 'Contacts',
  NEW_CONTACT: 'New Phone Book',
  EDIT_CONTACT: 'Edit Phone Book',
  SETTINGS: 'Settings',
  SETTINGS_ID: 'Settings ID',
  EMAIL: 'Email',
  NEW_EMAIL: 'New Email',
  EDIT_EMAIL: 'Edit Email',
  // Scale by moosbu
  CASHFLOW_TAB: 'CashFlow Tab',
  CASHFLOW_ADVANCE: 'CashFlow Advance',
  ACTIVE: 'Active',
  LOAN_HISTORY: 'Loan History',
  HOW_CREDIT_SCORE_WORKS: 'How it works',
  // others -> Shipping/Location
  SHIPPING_TAB: 'Shipping Tab',
  SHIPPING_LOCATION: 'Shipping/Location',
  SHIPPING: 'Shipping',
  NEW_SHIPPING: 'New Shipping',
  EDIT_SHIPPING: 'Edit Shipping',
  LOCATION: 'Location',
  NEW_LOCATION: 'New Location',
  EDIT_LOCATION: 'Edit Location',
  // others -> Customers
  CUSTOMERS_TAB: 'Customers Tab',
  CUSTOMERS: 'Customers',
  CUSTOMER_ORDER: 'Customer Order',
  CUSTOMER_ORDER_DETAILS: 'Customer Order Details',
};
