export default {
  HOME: 'Home Tab',
  WALLET: 'Wallet Tab',
  REWARD: 'Reward Tab',
  MORE: 'More Tab',
  MENU: 'Menu Tab',
  MENU_STACK: 'Menu Stack',
  MAIN: 'Main',
  // Auth
  LOGIN: 'Login',
  REGISTRATION: 'Registration',
  RESET_PASSWORD: 'Reset Password',
  RESET_PASSWORD_DONE: 'Reset Password Done',
  RESET_PASSWORD_SUCCESS: 'Reset Password Success',
  RESET_PASSWORD_FAIL: 'Reset Password Fail',
  CREATE_PASSWORD: 'Create Password',
  VERIFY_EMAIL: 'Verify Email',
  // Store front -> Analytic
  ANALYTICS: 'Analytics',
  SALES_ANALYTICS: 'Sales Analytics',
  PRODUCT_ANALYTICS: 'Product Analytics',
  CUSTOMER_ANALYTICS: 'Customer Analytics',
  // Store front -> Products
  PRODUCTS_TAB: 'Products Tab',
  PRODUCTS_STACK: 'Products Stack',
  PRODUCTS: 'Products',
  NEW_PRODUCT: 'New Product',
  EDIT_PRODUCT: 'Edit Product',
  // Store front -> Category
  CATEGORY: 'Category',
  NEW_CATEGORY: 'New Category',
  EDIT_CATEGORY: 'Edit Category',
  // Store front -> Coupon
  COUPON: 'Coupon screen',
  COUPON_TAB: 'Coupon tab',
  COUPON_DISCOUNT: 'Discount',
  COUPON_CODE: 'Coupon',
  COUPON_BUYXGETY: 'Buy X, get Y',
  NEW_COUPON: 'New Coupon',
  EDIT_COUPON: 'Edit coupon',
  NEW_DISCOUNT: 'New Discount',
  EDIT_DISCOUNT: 'Edit Dicount',
  NEW_BUYXGETY: 'New Buy x, Get y',
  EDIT_BUYXGETY: 'Edit Buy x, Get y',
  // Store front -> Tax
  TAX: 'Tax',
  TAX_TAB: 'Tax Tab',
  NEW_TAX: 'New Tax',
  EDIT_TAX: 'Edit Tax',
  // Marketing suite
  ENGAGEMNT_TAB: 'Engagement tab',
  ENGAGEMNT: 'Engagement',
  CAMPAIGN: 'Campaign',
  NEW_CAMPAIGN: 'Create New Campaign',
  EDIT_CAMPAIGN: 'Edit Campaign',
  PHONE_BOOK: 'Phone Book',
  NEW_PHONEBOOK: 'New Phone Book',
  EDIT_PHONEBOOK: 'Edit Phone Book',
  EMAIL: 'Email',
  NEW_EMAIL: 'New Email',
  EDIT_EMAIL: 'Edit Email',
  // Scale by moosbu
  CASHFLOW_TAB: 'CashFlow Tab',
  CASHFLOW_ADVANCE: 'CashFlow Advance',
  ACTIVE: 'Active',
  LOAN_HISTORY: 'Loan History',
  HOW_CREDIT_SCORE_WORKS: 'How it works',
  // others -> Shipping/Location
  SHIPPING_TAB: 'Shipping Tab',
  SHIPPING_LOCATION: 'Shipping/Location',
  SHIPPING: 'Shipping',
  NEW_SHIPPING: 'New Shipping',
  EDIT_SHIPPING: 'Edit Shipping',
  LOCATION: 'Location',
  NEW_LOCATION: 'New Location',
  EDIT_LOCATION: 'Edit Location',
  // others -> Customers
  CUSTOMERS_TAB: 'Customers Tab',
  CUSTOMERS: 'Customers',
  CUSTOMER_ORDER: 'Customer Order',
  CUSTOMER_ORDER_DETAILS: 'Customer Order Details',
};
