export default {
  HOME: 'Home Tab',
  MORE_STACK: 'More Tab',
  MENU: 'Menu Tab',
  MENU_STACK: 'Menu Stack',
  MAIN: 'Main',
  MAIN_STACK: 'Main Stack',
  PROFILE: 'Profile',
  AUTOMATION: 'Automation',
  M_BOT: 'M Bot',
  M_BOT_TAB: 'M Bot Tab',
  MARKET_PLACE: 'Public Listings',
  SUPPORT: 'Support',
  NOTIFICATIONS: 'Notifications',
  PAY_SUBSCRIPTION: 'Pay Subscription',
  // Reward
  REWARD: 'Reward Tab',
  REWARD_INFO: 'Reward info',
  // Integration
  INTEGRATION: 'Integration',
  PAYMENT_PROVIDER: 'Payment',
  AUTOMATED_PAYMENT: 'Automated Methods',
  MANUAL_PAYMENT: 'Manual Methods',
  LOGISTICS_PROVIDER: 'Logistics Provider',
  INBUILT_LOGISTICS: 'Inbuilt logistics',
  THIRDPARTY_LOGISTICS: 'Thirdparty logistics',
  // Store settings
  STORE_SETTINGS_STACK: 'Store Settings stack',
  STORE_SETTINGS: 'Store Settings',
  GENERAL_SETTINGS: 'General Settings',
  CURRENCY_SETTINGS: 'Currency Settings',
  // Business Registration
  BUSINESS_REGISTRATION: 'Bussiness Registration',
  BUSINESS_REGISTRATION_STACK: 'Bussiness Registration Stack',
  PROPRIETOR_INFO: 'Proprietor Information',
  PROPOSED_BUSINESS: 'Proposed Business',
  BVN_VERIFICATION: 'Bvn Verification',
  BILLING: 'Billing',
  // Auth
  LOGIN: 'Login',
  REGISTRATION: 'Registration',
  RESET_PASSWORD: 'Reset Password',
  RESET_PASSWORD_DONE: 'Reset Password Done',
  RESET_PASSWORD_SUCCESS: 'Reset Password Success',
  RESET_PASSWORD_FAIL: 'Reset Password Fail',
  CREATE_PASSWORD: 'Create Password',
  VERIFY_EMAIL: 'Verify Email',
  CHANGE_PASSWORD: 'Change Password',
  LOGOUT: 'Logout',
  // Wallet
  WALLET_STACK: 'Wallet Tab',
  WALLET: 'Wallet',
  CHOOSE_PAYMENT_METHOD: 'Choose payment method',
  BANK_TRANSFER: 'Bank Transfer',
  SEND_FUNDS: 'Send Funds',
  CONFIRM_TRANSFER_DETAILS: 'Confirm payment',
  WITHDRAW: 'Withdraw',
  ENTER_PIN: 'Enter pin',
  PAYOUT_SETTINGS: 'Payout Settings',
  // More
  MORE: 'More',
  // Store front -> Analytic
  ANALYTICS: 'Analytics',
  SALES_ANALYTICS: 'Sales Analytics',
  PRODUCT_ANALYTICS: 'Product Analytics',
  CUSTOMER_ANALYTICS: 'Customer Analytics',
  // Store front -> Products
  PRODUCTS_TAB: 'Products Tab',
  PRODUCTS_STACK: 'Products Stack',
  PRODUCTS: 'Products',
  NEW_PRODUCT: 'New Product',
  EDIT_PRODUCT: 'Edit Product',
  // Store front -> Category
  CATEGORY: 'Category',
  NEW_CATEGORY: 'New Category',
  EDIT_CATEGORY: 'Edit Category',
  // Store front -> Coupon
  COUPON: 'Coupon',
  // Store front -> Tax
  TAX: 'Tax',
  // Marketing suite
  ENGAGEMNT_TAB: 'Engagement tab',
  ENGAGEMNT: 'Engagement',
  CAMPAIGN: 'Campaign',
  NEW_CAMPAIGN: 'Create New Campaign',
  EDIT_CAMPAIGN: 'Edit Campaign',
  CONTACTS: 'Contact Groups',
  NEW_CONTACT: 'New Phone Book',
  EDIT_CONTACT: 'Edit Phone Book',
  SETTINGS: 'Settings',
  SETTINGS_ID: 'Settings ID',
  EMAIL: 'Email',
  NEW_EMAIL: 'New Email',
  EDIT_EMAIL: 'Edit Email',
  // Scale by moosbu
  CASHFLOW_TAB: 'CashFlow Tab',
  CASHFLOW_ADVANCE: 'CashFlow Advance',
  ACTIVE: 'Active',
  LOAN_HISTORY: 'Cash Flow History',
  HOW_CREDIT_SCORE_WORKS: 'How it works',
  CASHFLOW_BREAKDOWN: 'Cashflow breakdown',
  CASHFLOW_REASON: 'Cashflow Reason',
  PERSONAL_INFORMATION: 'Personal information',
  REFEREE: 'Referee',
  // others -> Shipping/Location
  SHIPPING_TAB: 'Shipping Tab',
  SHIPPING_LOCATION: 'Shipping/Location',
  SHIPPING: 'Shipping',
  SHIPPING_DETAILS: 'Shipping Details',
  SHIPPING_HISTORY: 'Shipping History',
  NEW_SHIPPING: 'New Shipping',
  EDIT_SHIPPING: 'Edit Shipping',
  LOCATION: 'Location',
  NEW_LOCATION: 'New Location',
  EDIT_LOCATION: 'Edit Location',
  // others -> Customers
  CUSTOMERS_TAB: 'Customers Tab',
  CUSTOMERS: 'Customers',
  CUSTOMER_ORDER: 'Customer Order',
  CUSTOMER_ORDER_DETAILS: 'Customer Order Details',
  // M bot
  SAVED_CONVERSATIONS: 'Saved Conversations',
  FAVOURITE_CONVERSATIONS: 'Favourite Conversations',
  CONVERSATION_TEMPLATES: 'Conversation Templates',
  CHAT: 'Chat',
  YEARLY_PLAN: 'Yearly Plan',
  MONTHLY_PLAN: 'Monthly Plan',
  PLAN: 'Plan',
};
